spring.mail.host=smtp-relay.sendinblue.com
spring.mail.port=587
spring.mail.username=khachansalah48@gmail.com
spring.mail.password=xsmtpsib-9e6b41e84263f46a3c877aabbc42dcb68f52d05347c83139d1dce76f8bb4cdac-UAGvsm5Hh1U4Xpvn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true